services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: enron_user
      POSTGRES_PASSWORD: enron_password
      POSTGRES_DB: enron_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  cleanerservice:
    build:
      context: .
      dockerfile: CleanerService/Dockerfile
    depends_on:
      - rabbitmq
      - seq
      - zipkin
      - postgres
    volumes:
      - ./litmus_maildir:/app/maildir:ro
    environment:
      - Seq__ServerUrl=http://seq:5341
      - Otlp__Endpoint=http://zipkin:9411/v1/traces
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__QueueName=cleaned_emails
      - Database__ConnectionString=Host=postgres;Database=enron_db;Username=enron_user;Password=enron_password

volumes:
  postgres_data: