version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false #disable security
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false #disable security
    depends_on:
      - elasticsearch

  cleaner_indexer:
    build:
      context: .
      dockerfile: Dockerfile.cleaner_indexer
    depends_on:
      - elasticsearch
    volumes:
      - ./litmus_maildir:/app/litmus_maildir:ro
      - ./litmus_cleaned_mails:/app/litmus_cleaned_mails

volumes:
  esdata: