services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: enron_user
      POSTGRES_PASSWORD: enron_password
      POSTGRES_DB: enron_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

volumes:
  postgres_data: