FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Cleaner.py .
COPY Indexer.py .
COPY litmus_maildir/ litmus_maildir/

CMD ["/bin/sh", "-c", "python Cleaner.py && python Indexer.py"]