global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cleaner_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cleaner_service:8087']
  
  - job_name: 'indexer_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['indexer_service:8088']

  - job_name: 'search_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['search_api:8089']
