#FROM nginx:latest
#
## Copy custom Nginx config
#COPY web-ui/nginx.conf/nginx.conf /etc/nginx/nginx.conf
#
## Copy built Angular files into Nginx serving directory
#COPY web-ui/www usr/share/nginx/html
#
#EXPOSE 80
#
#CMD ["nginx", "-g", "daemon off;"]
