// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedLibrary;

#nullable disable

namespace SharedLibrary.Migrations
{
    [DbContext(typeof(DbContextConfig))]
    partial class DbContextConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLibrary.Models.FileEntity", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SharedLibrary.Models.Occurrence", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("FileId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("WordId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("SharedLibrary.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordId"));

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("WordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SharedLibrary.Models.Occurrence", b =>
                {
                    b.HasOne("SharedLibrary.Models.FileEntity", "File")
                        .WithMany("Occurrences")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibrary.Models.Word", "Word")
                        .WithMany("Occurrences")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("SharedLibrary.Models.FileEntity", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("SharedLibrary.Models.Word", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
